import type { Customer, Site, Contact, Device, Intervention, Task, User } from '@/types'

// ============================================================
// CUSTOMERS (billing entities)
// ============================================================

export const customers: Customer[] = [
  {
    id: 'c1',
    name: 'Rustoord Ennea',
    phone: '03 776 12 34',
    address: 'Gasthuisstraat 12',
    city: 'Sint-Niklaas',
    vatNumber: 'BE0412345678',
  },
  {
    id: 'c2',
    name: 'WZC Helianthus',
    phone: '09 252 67 89',
    address: 'Wellingstraat 5',
    city: 'Melle',
    vatNumber: 'BE0498765432',
  },
  {
    id: 'c3',
    name: 'AZ Nikolaas',
    phone: '03 760 00 00',
    address: 'Moerlandstraat 1',
    city: 'Sint-Niklaas',
    vatNumber: 'BE0455112233',
  },
  {
    id: 'c4',
    name: "Frituur 't Pleintje",
    phone: '09 348 55 12',
    address: 'Markt 18',
    city: 'Lokeren',
    vatNumber: 'BE0678901234',
  },
  {
    id: 'c5',
    name: 'Brasserie De Klok',
    phone: '052 21 33 44',
    address: 'Kerkstraat 10',
    city: 'Dendermonde',
    vatNumber: 'BE0789012345',
  },
  {
    id: 'c6',
    name: 'Hotel Scheldezicht',
    phone: '03 889 41 20',
    address: 'Kaai 4',
    city: 'Temse',
    vatNumber: 'BE0544123456',
  },
  {
    id: 'c7',
    name: 'Bakkerij Van Hove',
    phone: '03 771 55 90',
    address: 'Stationsstraat 88',
    city: 'Sint-Niklaas',
    vatNumber: 'BE0523344556',
  },
  {
    id: 'c8',
    name: 'Campus De Horizon',
    phone: '09 332 18 20',
    address: 'Schooldreef 3',
    city: 'Aalst',
    vatNumber: 'BE0478123499',
  },
  {
    id: 'c9',
    name: 'Slagerij Vermeulen',
    phone: '09 278 43 11',
    address: 'Kasteelstraat 22',
    city: 'Wetteren',
    vatNumber: 'BE0667123401',
  },
  {
    id: 'c10',
    name: 'WZC Lindepark',
    phone: '052 30 11 22',
    address: 'Lindelaan 15',
    city: 'Lebbeke',
    vatNumber: 'BE0432987611',
  },
  {
    id: 'c11',
    name: 'Bistro De Markt',
    phone: '09 344 77 21',
    address: 'Marktplein 7',
    city: 'Eeklo',
    vatNumber: 'BE0711223344',
  },
  {
    id: 'c12',
    name: 'Ziekenhuis Sint-Blasius',
    phone: '052 25 25 25',
    address: 'Kroonveldlaan 50',
    city: 'Dendermonde',
    vatNumber: 'BE0401122233',
  },
  {
    id: 'c13',
    name: 'Fresco Catering',
    phone: '03 345 66 77',
    address: 'Industrieweg 31',
    city: 'Beveren',
    vatNumber: 'BE0699234512',
  },
  {
    id: 'c14',
    name: 'Sportcentrum Meulenberg',
    phone: '09 221 44 90',
    address: 'Sportlaan 9',
    city: 'Lochristi',
    vatNumber: 'BE0501456789',
  },
  {
    id: 'c15',
    name: 'Pizzeria Da Luca',
    phone: '03 765 89 10',
    address: 'Nieuwstraat 14',
    city: 'Lokeren',
    vatNumber: 'BE0734455667',
  },
]

// ============================================================
// SITES (physical locations — where the work happens)
// ============================================================

export const sites: Site[] = [
  // Rustoord Ennea has one site (same address as customer)
  {
    id: 's1',
    customerId: 'c1',
    name: 'Rustoord Ennea',
    address: 'Gasthuisstraat 12',
    city: 'Sint-Niklaas',
    phones: ['03 776 12 34', '03 776 12 35'],
    lat: 51.1286,
    lon: 4.2130,
  },

  // WZC Helianthus has two sites
  {
    id: 's2',
    customerId: 'c2',
    name: 'WZC Helianthus — Melle',
    address: 'Wellingstraat 5',
    city: 'Melle',
    phones: ['09 252 67 89'],
    lat: 51.0030,
    lon: 3.7989,
  },
  {
    id: 's3',
    customerId: 'c2',
    name: 'WZC Helianthus — Merelbeke',
    address: 'Hundelgemsesteenweg 44',
    city: 'Merelbeke',
    phones: ['09 231 44 56', '09 231 44 57'],
    lat: 51.0249,
    lon: 3.7491,
  },

  // AZ Nikolaas has one site
  {
    id: 's4',
    customerId: 'c3',
    name: 'AZ Nikolaas — Campus Sint-Niklaas',
    address: 'Moerlandstraat 1',
    city: 'Sint-Niklaas',
    phones: ['03 760 00 00'],
    lat: 51.1616,
    lon: 4.1493,
  },

  // Frituur 't Pleintje in Lokeren
  {
    id: 's5',
    customerId: 'c4',
    name: "Frituur 't Pleintje",
    address: 'Markt 18',
    city: 'Lokeren',
    phones: ['09 348 55 12'],
    lat: 51.1040,
    lon: 3.9892,
  },

  // Brasserie De Klok in Dendermonde
  {
    id: 's6',
    customerId: 'c5',
    name: 'Brasserie De Klok',
    address: 'Kerkstraat 10',
    city: 'Dendermonde',
    phones: ['052 21 33 44'],
    lat: 51.0317,
    lon: 4.0983,
  },
  {
    id: 's7',
    customerId: 'c6',
    name: 'Hotel Scheldezicht',
    address: 'Kaai 4',
    city: 'Temse',
    phones: ['03 889 41 20'],
    lat: 51.1261,
    lon: 4.2145,
  },
  {
    id: 's8',
    customerId: 'c7',
    name: 'Bakkerij Van Hove',
    address: 'Stationsstraat 88',
    city: 'Sint-Niklaas',
    phones: ['03 771 55 90'],
    lat: 51.1634,
    lon: 4.1437,
  },
  {
    id: 's9',
    customerId: 'c8',
    name: 'Campus De Horizon',
    address: 'Schooldreef 3',
    city: 'Aalst',
    phones: ['09 332 18 20'],
    lat: 50.9385,
    lon: 4.0403,
  },
  {
    id: 's10',
    customerId: 'c9',
    name: 'Slagerij Vermeulen',
    address: 'Kasteelstraat 22',
    city: 'Wetteren',
    phones: ['09 278 43 11'],
    lat: 51.0009,
    lon: 3.8814,
  },
  {
    id: 's11',
    customerId: 'c10',
    name: 'WZC Lindepark',
    address: 'Lindelaan 15',
    city: 'Lebbeke',
    phones: ['052 30 11 22', '052 30 11 23'],
    lat: 51.0058,
    lon: 4.1346,
  },
  {
    id: 's12',
    customerId: 'c11',
    name: 'Bistro De Markt',
    address: 'Marktplein 7',
    city: 'Eeklo',
    phones: ['09 344 77 21'],
    lat: 51.1872,
    lon: 3.5668,
  },
  {
    id: 's13',
    customerId: 'c12',
    name: 'Ziekenhuis Sint-Blasius',
    address: 'Kroonveldlaan 50',
    city: 'Dendermonde',
    phones: ['052 25 25 25'],
    lat: 51.0241,
    lon: 4.1008,
  },
  {
    id: 's14',
    customerId: 'c13',
    name: 'Fresco Catering — Productie',
    address: 'Industrieweg 31',
    city: 'Beveren',
    phones: ['03 345 66 77'],
    lat: 51.2087,
    lon: 4.2558,
  },
  {
    id: 's15',
    customerId: 'c13',
    name: 'Fresco Catering — Satellietkeuken',
    address: 'Havenlaan 18',
    city: 'Beveren',
    phones: ['03 345 66 78'],
    lat: 51.2101,
    lon: 4.2675,
  },
  {
    id: 's16',
    customerId: 'c14',
    name: 'Sportcentrum Meulenberg',
    address: 'Sportlaan 9',
    city: 'Lochristi',
    phones: ['09 221 44 90'],
    lat: 51.1079,
    lon: 3.8339,
  },
  {
    id: 's17',
    customerId: 'c15',
    name: 'Pizzeria Da Luca',
    address: 'Nieuwstraat 14',
    city: 'Lokeren',
    phones: ['03 765 89 10'],
    lat: 51.1049,
    lon: 3.9947,
  },
]

// ============================================================
// CONTACTS (per site)
// ============================================================

export const contacts: Contact[] = [
  {
    id: 'ct1',
    siteId: 's1',
    name: 'Marie Declercq',
    phone: '0478 12 34 56',
    email: 'marie.declercq@ennea.be',
    role: 'Verantwoordelijke keuken',
  },
  {
    id: 'ct2',
    siteId: 's2',
    name: 'Luc Van den Berg',
    phone: '0495 23 45 67',
    role: 'Technieker ter plaatse',
  },
  {
    id: 'ct3',
    siteId: 's3',
    name: 'Sofie Janssens',
    phone: '0472 98 76 54',
    email: 'sofie.janssens@helianthus.be',
    role: 'Verantwoordelijke',
  },
  {
    id: 'ct4',
    siteId: 's4',
    name: 'Peter Goossens',
    phone: '0499 11 22 33',
    email: 'p.goossens@azniko.be',
    role: 'Facility manager',
  },
  {
    id: 'ct5',
    siteId: 's5',
    name: 'Kevin Maes',
    phone: '0476 33 44 55',
    role: 'Uitbater',
  },
  {
    id: 'ct6',
    siteId: 's6',
    name: 'Annelies De Smet',
    phone: '0487 66 77 88',
    email: 'annelies@deklok.be',
    role: 'Zaakvoerster',
  },
  { id: 'ct7', siteId: 's7', name: 'Tom Verbruggen', phone: '0471 22 33 44', email: 'tom@scheldezicht.be', role: 'Chef keuken' },
  { id: 'ct8', siteId: 's8', name: 'Liesbeth Van Hove', phone: '0479 88 77 66', role: 'Zaakvoerder' },
  { id: 'ct9', siteId: 's9', name: 'Koen Martens', phone: '0484 91 12 13', email: 'koen.martens@horizon.be', role: 'Technisch coördinator' },
  { id: 'ct10', siteId: 's10', name: 'Dirk Vermeulen', phone: '0475 34 12 90', role: 'Uitbater' },
  { id: 'ct11', siteId: 's11', name: 'Mia De Winter', phone: '0488 01 22 33', email: 'mia@lindepark.be', role: 'Hoofdkeuken' },
  { id: 'ct12', siteId: 's12', name: 'Niels Pieters', phone: '0472 44 18 52', role: 'Chef' },
  { id: 'ct13', siteId: 's13', name: 'Karen Bogaert', phone: '0496 13 25 25', email: 'k.bogaert@sintblasius.be', role: 'Facility manager' },
  { id: 'ct14', siteId: 's14', name: 'Ilias Rahmani', phone: '0470 66 44 31', role: 'Productieverantwoordelijke' },
  { id: 'ct15', siteId: 's15', name: 'Els De Backer', phone: '0477 31 22 19', role: 'Site supervisor' },
  { id: 'ct16', siteId: 's16', name: 'Bart Van Mol', phone: '0489 54 31 26', role: 'Technisch beheerder' },
  { id: 'ct17', siteId: 's17', name: 'Luca Romano', phone: '0478 45 90 11', role: 'Zaakvoerder' },
]

// ============================================================
// DEVICES (per site)
// ============================================================

export const devices: Device[] = [
  // Rustoord Ennea (s1)
  {
    id: 'd1',
    siteId: 's1',
    brand: 'Electrolux',
    model: 'Glasswasher 50',
    serialNumber: 'ELX-2019-00123',
    installDate: '2019-03-15',
  },
  {
    id: 'd2',
    siteId: 's1',
    brand: 'Rational',
    model: 'SelfCooking Center 61',
    serialNumber: 'RAT-2020-00456',
    installDate: '2020-06-01',
    notes: 'Regelmatig kalkaanslag op stoomgenerator',
  },

  // WZC Helianthus Melle (s2)
  {
    id: 'd3',
    siteId: 's2',
    brand: 'Rational',
    model: 'iCombi Pro 10-1/1',
    serialNumber: 'RAT-2021-00789',
    installDate: '2021-09-10',
  },
  {
    id: 'd4',
    siteId: 's2',
    brand: 'Meiko',
    model: 'FV 130.2',
    serialNumber: 'MEI-2018-00321',
    installDate: '2018-11-20',
    notes: 'Pomp vervangen in 2022',
  },

  // WZC Helianthus Merelbeke (s3)
  {
    id: 'd5',
    siteId: 's3',
    brand: 'MKN',
    model: 'FlexiCombi 10.1',
    serialNumber: 'MKN-2022-00654',
    installDate: '2022-02-14',
  },

  // AZ Nikolaas (s4)
  {
    id: 'd6',
    siteId: 's4',
    brand: 'Winterhalter',
    model: 'UC-M',
    serialNumber: 'WIN-2020-00987',
    installDate: '2020-01-08',
  },
  {
    id: 'd7',
    siteId: 's4',
    brand: 'Rational',
    model: 'iCombi Pro 20-1/1',
    serialNumber: 'RAT-2023-01234',
    installDate: '2023-05-22',
    notes: 'Groot toestel — 2 techniekers nodig voor onderhoud',
  },

  // Frituur 't Pleintje (s5)
  {
    id: 'd8',
    siteId: 's5',
    brand: 'Henny Penny',
    model: 'OFG-322',
    serialNumber: 'HP-2021-00555',
    installDate: '2021-04-10',
    notes: 'Open fryer — hogedruk gasaansluiting',
  },

  // Brasserie De Klok (s6)
  {
    id: 'd9',
    siteId: 's6',
    brand: 'Rational',
    model: 'iCombi Classic 6-1/1',
    serialNumber: 'RAT-2022-00888',
    installDate: '2022-08-15',
  },
  { id: 'd10', siteId: 's1', brand: 'Winterhalter', model: 'PT-L', serialNumber: 'WIN-2021-01111', installDate: '2021-02-18' },
  { id: 'd11', siteId: 's1', brand: 'MKN', model: 'SpaceCombi 6', serialNumber: 'MKN-2023-02222', installDate: '2023-03-12' },
  { id: 'd12', siteId: 's1', brand: 'Electrolux', model: 'Thermaline 80', serialNumber: 'ELX-2017-03030', installDate: '2017-10-05', notes: 'Kooklijn warm gedeelte' },
  { id: 'd13', siteId: 's2', brand: 'Rational', model: 'iVario Pro 2-S', serialNumber: 'RAT-2022-01555', installDate: '2022-05-07' },
  { id: 'd14', siteId: 's2', brand: 'Winterhalter', model: 'MTF', serialNumber: 'WIN-2019-01666', installDate: '2019-11-19' },
  { id: 'd15', siteId: 's2', brand: 'Electrolux', model: 'SkyLine Blast Chiller', serialNumber: 'ELX-2021-01777', installDate: '2021-08-09' },
  { id: 'd16', siteId: 's3', brand: 'Electrolux', model: 'SkyLine Pro 20GN', serialNumber: 'ELX-2020-01888', installDate: '2020-01-22' },
  { id: 'd17', siteId: 's3', brand: 'Meiko', model: 'M-iClean H', serialNumber: 'MEI-2021-01999', installDate: '2021-04-01' },
  { id: 'd18', siteId: 's4', brand: 'Convotherm', model: 'maxx pro 10.10', serialNumber: 'CON-2021-02020', installDate: '2021-07-14' },
  { id: 'd19', siteId: 's4', brand: 'Hobart', model: 'PREMAX AUP', serialNumber: 'HOB-2019-02121', installDate: '2019-09-16' },
  { id: 'd20', siteId: 's4', brand: 'Rational', model: 'iVario 4-2', serialNumber: 'RAT-2024-02223', installDate: '2024-02-12' },
  { id: 'd21', siteId: 's5', brand: 'Pitco', model: 'SG14R', serialNumber: 'PIT-2020-02323', installDate: '2020-05-10' },
  { id: 'd22', siteId: 's5', brand: 'FriFri', model: 'Vision 422', serialNumber: 'FRI-2018-02424', installDate: '2018-06-17' },
  { id: 'd23', siteId: 's6', brand: 'Winterhalter', model: 'UF-L', serialNumber: 'WIN-2021-02525', installDate: '2021-03-11' },
  { id: 'd24', siteId: 's6', brand: 'Electrolux', model: 'SkyLine PremiumS 10GN', serialNumber: 'ELX-2024-02626', installDate: '2024-01-08' },
  { id: 'd25', siteId: 's7', brand: 'Rational', model: 'iCombi Pro 6-1/1', serialNumber: 'RAT-2021-02727', installDate: '2021-06-18' },
  { id: 'd26', siteId: 's7', brand: 'Winterhalter', model: 'UC-XL', serialNumber: 'WIN-2022-02828', installDate: '2022-09-23' },
  { id: 'd27', siteId: 's8', brand: 'Sveba Dahlen', model: 'DC-2', serialNumber: 'SVE-2019-02929', installDate: '2019-04-27' },
  { id: 'd28', siteId: 's8', brand: 'Bongard', model: '8.84 E', serialNumber: 'BON-2020-03031', installDate: '2020-11-03' },
  { id: 'd29', siteId: 's9', brand: 'MKN', model: 'FlexiChef 2', serialNumber: 'MKN-2022-03131', installDate: '2022-03-21' },
  { id: 'd30', siteId: 's9', brand: 'Rational', model: 'iCombi Pro 20-2/1', serialNumber: 'RAT-2023-03232', installDate: '2023-10-10' },
  { id: 'd31', siteId: 's10', brand: 'Hobart', model: 'FXL', serialNumber: 'HOB-2018-03333', installDate: '2018-02-14' },
  { id: 'd32', siteId: 's10', brand: 'Rational', model: 'SelfCooking Center 101', serialNumber: 'RAT-2017-03434', installDate: '2017-05-09' },
  { id: 'd33', siteId: 's11', brand: 'Electrolux', model: 'SkyLine ChillS 50kg', serialNumber: 'ELX-2022-03535', installDate: '2022-08-30' },
  { id: 'd34', siteId: 's11', brand: 'Rational', model: 'iCombi Pro 10-1/1', serialNumber: 'RAT-2020-03636', installDate: '2020-10-18' },
  { id: 'd35', siteId: 's11', brand: 'Meiko', model: 'M-iQ', serialNumber: 'MEI-2021-03737', installDate: '2021-12-02' },
  { id: 'd36', siteId: 's12', brand: 'PizzaMaster', model: 'PM 452', serialNumber: 'PIZ-2023-03838', installDate: '2023-04-06' },
  { id: 'd37', siteId: 's12', brand: 'Winterhalter', model: 'PT-XL', serialNumber: 'WIN-2021-03939', installDate: '2021-09-14' },
  { id: 'd38', siteId: 's13', brand: 'Rational', model: 'iCombi Pro 20-1/1', serialNumber: 'RAT-2022-04040', installDate: '2022-01-18' },
  { id: 'd39', siteId: 's13', brand: 'Hobart', model: 'PREMAX CP', serialNumber: 'HOB-2019-04141', installDate: '2019-03-25' },
  { id: 'd40', siteId: 's14', brand: 'Electrolux', model: 'SkyLine Pro 6GN', serialNumber: 'ELX-2021-04242', installDate: '2021-06-09' },
  { id: 'd41', siteId: 's14', brand: 'Rational', model: 'iVario Pro L', serialNumber: 'RAT-2024-04343', installDate: '2024-02-20' },
  { id: 'd42', siteId: 's15', brand: 'Meiko', model: 'UPster H 500', serialNumber: 'MEI-2020-04444', installDate: '2020-07-07' },
  { id: 'd43', siteId: 's15', brand: 'MKN', model: 'FlexiChef 1', serialNumber: 'MKN-2019-04545', installDate: '2019-08-11' },
  { id: 'd44', siteId: 's16', brand: 'Hoshizaki', model: 'FM-170AKE', serialNumber: 'HOS-2021-04646', installDate: '2021-01-12' },
  { id: 'd45', siteId: 's16', brand: 'Winterhalter', model: 'UC-L', serialNumber: 'WIN-2020-04747', installDate: '2020-05-16' },
  { id: 'd46', siteId: 's17', brand: 'Moretti Forni', model: 'T64E', serialNumber: 'MOR-2022-04848', installDate: '2022-04-28' },
  { id: 'd47', siteId: 's17', brand: 'Meiko', model: 'M-iClean UM', serialNumber: 'MEI-2023-04949', installDate: '2023-09-01' },
]

// ============================================================
// INTERVENTIONS (pre-assigned by admin — demo data)
// ============================================================

export const interventions: Intervention[] = [
  {
    id: 'i1',
    customerId: 'c1',
    customerName: 'Rustoord Ennea',
    siteId: 's1',
    siteName: 'Rustoord Ennea',
    siteAddress: 'Gasthuisstraat 12',
    siteCity: 'Sint-Niklaas',
    siteLat: 51.1286,
    siteLon: 4.2130,
    deviceId: 'd1',
    deviceBrand: 'Electrolux',
    deviceModel: 'Glasswasher 50',
    plannedDate: new Date().toISOString(),
    status: 'gepland',
    type: 'warm',
    description: 'Vaat wordt niet proper — resten blijven achter na wascyclus',
    estimatedMinutes: 120,
    isUrgent: false,
    source: 'planned',
    technicians: [
      { technicianId: 'u1', name: 'Olivier Bossuyt', initials: 'OB', isLead: true, accepted: true, plannedOrder: 1 },
    ],
  },
  {
    id: 'i2',
    customerId: 'c2',
    customerName: 'WZC Helianthus',
    siteId: 's2',
    siteName: 'WZC Helianthus — Melle',
    siteAddress: 'Wellingstraat 5',
    siteCity: 'Melle',
    siteLat: 51.0030,
    siteLon: 3.7989,
    deviceId: 'd3',
    deviceBrand: 'Rational',
    deviceModel: 'iCombi Pro 10-1/1',
    plannedDate: new Date().toISOString(),
    status: 'gepland',
    type: 'montage',
    description: 'Installatie waterontharder',
    estimatedMinutes: 60,
    isUrgent: false,
    source: 'planned',
    technicians: [
      { technicianId: 'u1', name: 'Olivier Bossuyt', initials: 'OB', isLead: true, accepted: true, plannedOrder: 2 },
      { technicianId: 'u2', name: 'Jonas Declercq', initials: 'JD', isLead: false, accepted: true, plannedOrder: 2 },
    ],
  },
  {
    id: 'i3',
    customerId: 'c3',
    customerName: 'AZ Nikolaas',
    siteId: 's4',
    siteName: 'AZ Nikolaas — Campus Sint-Niklaas',
    siteAddress: 'Moerlandstraat 1',
    siteCity: 'Sint-Niklaas',
    siteLat: 51.1616,
    siteLon: 4.1493,
    deviceId: 'd7',
    deviceBrand: 'Rational',
    deviceModel: 'iCombi Pro 20-1/1',
    plannedDate: new Date().toISOString(),
    status: 'gepland',
    type: 'preventief',
    description: 'Jaarlijks onderhoud groot toestel',
    estimatedMinutes: 150,
    isUrgent: false,
    source: 'planned',
    technicians: [
      { technicianId: 'u1', name: 'Olivier Bossuyt', initials: 'OB', isLead: true, accepted: true, plannedOrder: 3 },
    ],
  },
  {
    id: 'i4',
    customerId: 'c1',
    customerName: 'Rustoord Ennea',
    siteId: 's1',
    siteName: 'Rustoord Ennea',
    siteAddress: 'Gasthuisstraat 12',
    siteCity: 'Sint-Niklaas',
    siteLat: 51.1286,
    siteLon: 4.2130,
    deviceId: 'd2',
    deviceBrand: 'Rational',
    deviceModel: 'SelfCooking Center 61',
    plannedDate: new Date().toISOString(),
    status: 'gepland',
    type: 'warm',
    description: 'Ontkalking stoomgenerator',
    estimatedMinutes: 90,
    isUrgent: false,
    source: 'planned',
    technicians: [
      { technicianId: 'u1', name: 'Olivier Bossuyt', initials: 'OB', isLead: true, accepted: true, plannedOrder: 4 },
    ],
  },
  {
    id: 'i5',
    customerId: 'c4',
    customerName: "Frituur 't Pleintje",
    siteId: 's5',
    siteName: "Frituur 't Pleintje",
    siteAddress: 'Markt 18',
    siteCity: 'Lokeren',
    siteLat: 51.1040,
    siteLon: 3.9892,
    deviceId: 'd8',
    deviceBrand: 'Henny Penny',
    deviceModel: 'OFG-322',
    plannedDate: new Date().toISOString(),
    status: 'gepland',
    type: 'warm',
    description: 'Friteuse schakelt uit na 10 min — thermokoppel defect?',
    estimatedMinutes: 90,
    isUrgent: true,
    source: 'planned',
    technicians: [
      { technicianId: 'u1', name: 'Olivier Bossuyt', initials: 'OB', isLead: true, accepted: true, plannedOrder: 5 },
    ],
  },
  {
    id: 'i6',
    customerId: 'c5',
    customerName: 'Brasserie De Klok',
    siteId: 's6',
    siteName: 'Brasserie De Klok',
    siteAddress: 'Kerkstraat 10',
    siteCity: 'Dendermonde',
    siteLat: 51.0317,
    siteLon: 4.0983,
    deviceId: 'd9',
    deviceBrand: 'Rational',
    deviceModel: 'iCombi Classic 6-1/1',
    plannedDate: new Date().toISOString(),
    status: 'gepland',
    type: 'preventief',
    description: 'Halfjaarlijks onderhoud combisteamer',
    estimatedMinutes: 60,
    isUrgent: false,
    source: 'planned',
    technicians: [
      { technicianId: 'u1', name: 'Olivier Bossuyt', initials: 'OB', isLead: true, accepted: true, plannedOrder: 6 },
    ],
  },
  // --- Open pool — flexibele extra jobs die de technieker zelf kan oppikken ---
  {
    id: 'i7',
    customerId: 'c2',
    customerName: 'WZC Helianthus',
    siteId: 's3',
    siteName: 'WZC Helianthus — Merelbeke',
    siteAddress: 'Hundelgemsesteenweg 44',
    siteCity: 'Merelbeke',
    siteLat: 51.0249,
    siteLon: 3.7491,
    deviceId: 'd5',
    deviceBrand: 'MKN',
    deviceModel: 'FlexiCombi 10.1',
    plannedDate: new Date().toISOString(),
    status: 'gepland',
    type: 'warm',
    description: 'Stoomt opnieuw niet — foutcode E-07 op display',
    estimatedMinutes: 180,
    isUrgent: true,
    source: 'reactive',
    technicians: [
      { technicianId: 'u2', name: 'Jonas Declercq', initials: 'JD', isLead: true, accepted: false, plannedOrder: 0 },
    ],
  },
  {
    id: 'i8',
    customerId: 'c2',
    customerName: 'WZC Helianthus',
    siteId: 's2',
    siteName: 'WZC Helianthus — Melle',
    siteAddress: 'Wellingstraat 5',
    siteCity: 'Melle',
    siteLat: 51.0030,
    siteLon: 3.7989,
    deviceId: 'd4',
    deviceBrand: 'Meiko',
    deviceModel: 'FV 130.2',
    plannedDate: new Date().toISOString(),
    status: 'gepland',
    type: 'warm',
    description: 'Pomp maakt geluid — check dringend',
    estimatedMinutes: 60,
    isUrgent: false,
    source: 'reactive',
    technicians: [
      { technicianId: 'u1', name: 'Olivier Bossuyt', initials: 'OB', isLead: true, accepted: false, plannedOrder: 0 },
    ],
  },
  {
    id: 'i9',
    customerId: 'c1',
    customerName: 'Rustoord Ennea',
    siteId: 's1',
    siteName: 'Rustoord Ennea',
    siteAddress: 'Gasthuisstraat 12',
    siteCity: 'Sint-Niklaas',
    siteLat: 51.1286,
    siteLon: 4.2130,
    deviceId: 'd10',
    deviceBrand: 'Winterhalter',
    deviceModel: 'PT-L',
    plannedDate: '2026-02-11T08:30:00.000Z',
    status: 'afgewerkt',
    type: 'preventief',
    description: 'Preventief onderhoud doorschuifvaatwasser',
    estimatedMinutes: 95,
    isUrgent: false,
    source: 'planned',
    technicians: [
      { technicianId: 'u1', name: 'Olivier Bossuyt', initials: 'OB', isLead: true, accepted: true, plannedOrder: 1 },
    ],
  },
  {
    id: 'i10',
    customerId: 'c1',
    customerName: 'Rustoord Ennea',
    siteId: 's1',
    siteName: 'Rustoord Ennea',
    siteAddress: 'Gasthuisstraat 12',
    siteCity: 'Sint-Niklaas',
    siteLat: 51.1286,
    siteLon: 4.2130,
    deviceId: 'd11',
    deviceBrand: 'MKN',
    deviceModel: 'SpaceCombi 6',
    plannedDate: '2025-12-03T09:15:00.000Z',
    status: 'afgewerkt',
    type: 'warm',
    description: 'Deurpakking vervangen na stoomlek',
    estimatedMinutes: 70,
    isUrgent: false,
    source: 'planned',
    technicians: [
      { technicianId: 'u2', name: 'Jonas Declercq', initials: 'JD', isLead: true, accepted: true, plannedOrder: 1 },
    ],
  },
  {
    id: 'i11',
    customerId: 'c2',
    customerName: 'WZC Helianthus',
    siteId: 's2',
    siteName: 'WZC Helianthus — Melle',
    siteAddress: 'Wellingstraat 5',
    siteCity: 'Melle',
    siteLat: 51.0030,
    siteLon: 3.7989,
    deviceId: 'd14',
    deviceBrand: 'Winterhalter',
    deviceModel: 'MTF',
    plannedDate: '2026-01-20T10:00:00.000Z',
    status: 'afgewerkt',
    type: 'warm',
    description: 'Aandrijfmotor transportband vervangen',
    estimatedMinutes: 130,
    isUrgent: true,
    source: 'planned',
    technicians: [
      { technicianId: 'u1', name: 'Olivier Bossuyt', initials: 'OB', isLead: true, accepted: true, plannedOrder: 1 },
    ],
  },
  {
    id: 'i12',
    customerId: 'c2',
    customerName: 'WZC Helianthus',
    siteId: 's3',
    siteName: 'WZC Helianthus — Merelbeke',
    siteAddress: 'Hundelgemsesteenweg 44',
    siteCity: 'Merelbeke',
    siteLat: 51.0249,
    siteLon: 3.7491,
    deviceId: 'd16',
    deviceBrand: 'Electrolux',
    deviceModel: 'SkyLine Pro 20GN',
    plannedDate: '2025-11-18T08:00:00.000Z',
    status: 'afgewerkt',
    type: 'preventief',
    description: 'Preventief onderhoud combisteamer',
    estimatedMinutes: 120,
    isUrgent: false,
    source: 'planned',
    technicians: [
      { technicianId: 'u2', name: 'Jonas Declercq', initials: 'JD', isLead: true, accepted: true, plannedOrder: 1 },
    ],
  },
  {
    id: 'i13',
    customerId: 'c3',
    customerName: 'AZ Nikolaas',
    siteId: 's4',
    siteName: 'AZ Nikolaas — Campus Sint-Niklaas',
    siteAddress: 'Moerlandstraat 1',
    siteCity: 'Sint-Niklaas',
    siteLat: 51.1616,
    siteLon: 4.1493,
    deviceId: 'd19',
    deviceBrand: 'Hobart',
    deviceModel: 'PREMAX AUP',
    plannedDate: '2026-03-02T07:45:00.000Z',
    status: 'afgewerkt',
    type: 'warm',
    description: 'Afpompstoring opgelost en niveausensor gereinigd',
    estimatedMinutes: 85,
    isUrgent: false,
    source: 'planned',
    technicians: [
      { technicianId: 'u1', name: 'Olivier Bossuyt', initials: 'OB', isLead: true, accepted: true, plannedOrder: 1 },
    ],
  },
  {
    id: 'i14',
    customerId: 'c3',
    customerName: 'AZ Nikolaas',
    siteId: 's4',
    siteName: 'AZ Nikolaas — Campus Sint-Niklaas',
    siteAddress: 'Moerlandstraat 1',
    siteCity: 'Sint-Niklaas',
    siteLat: 51.1616,
    siteLon: 4.1493,
    deviceId: 'd18',
    deviceBrand: 'Convotherm',
    deviceModel: 'maxx pro 10.10',
    plannedDate: '2025-10-22T12:30:00.000Z',
    status: 'afgewerkt',
    type: 'warm',
    description: 'Ventilatormotor vervangen na oververhitting',
    estimatedMinutes: 160,
    isUrgent: true,
    source: 'planned',
    technicians: [
      { technicianId: 'u2', name: 'Jonas Declercq', initials: 'JD', isLead: true, accepted: true, plannedOrder: 1 },
    ],
  },
  {
    id: 'i15',
    customerId: 'c4',
    customerName: "Frituur 't Pleintje",
    siteId: 's5',
    siteName: "Frituur 't Pleintje",
    siteAddress: 'Markt 18',
    siteCity: 'Lokeren',
    siteLat: 51.1040,
    siteLon: 3.9892,
    deviceId: 'd21',
    deviceBrand: 'Pitco',
    deviceModel: 'SG14R',
    plannedDate: '2026-01-08T09:40:00.000Z',
    status: 'afgewerkt',
    type: 'warm',
    description: 'Thermostaat vervangen en herafgesteld',
    estimatedMinutes: 75,
    isUrgent: false,
    source: 'planned',
    technicians: [
      { technicianId: 'u1', name: 'Olivier Bossuyt', initials: 'OB', isLead: true, accepted: true, plannedOrder: 1 },
    ],
  },
  {
    id: 'i16',
    customerId: 'c5',
    customerName: 'Brasserie De Klok',
    siteId: 's6',
    siteName: 'Brasserie De Klok',
    siteAddress: 'Kerkstraat 10',
    siteCity: 'Dendermonde',
    siteLat: 51.0317,
    siteLon: 4.0983,
    deviceId: 'd23',
    deviceBrand: 'Winterhalter',
    deviceModel: 'UF-L',
    plannedDate: '2025-12-15T14:10:00.000Z',
    status: 'afgewerkt',
    type: 'preventief',
    description: 'Jaarlijks onderhoud onderbouwvaatwasser',
    estimatedMinutes: 60,
    isUrgent: false,
    source: 'planned',
    technicians: [
      { technicianId: 'u2', name: 'Jonas Declercq', initials: 'JD', isLead: true, accepted: true, plannedOrder: 1 },
    ],
  },
  {
    id: 'i17',
    customerId: 'c5',
    customerName: 'Brasserie De Klok',
    siteId: 's6',
    siteName: 'Brasserie De Klok',
    siteAddress: 'Kerkstraat 10',
    siteCity: 'Dendermonde',
    siteLat: 51.0317,
    siteLon: 4.0983,
    deviceId: 'd24',
    deviceBrand: 'Electrolux',
    deviceModel: 'SkyLine PremiumS 10GN',
    plannedDate: '2026-02-26T08:20:00.000Z',
    status: 'afgewerkt',
    type: 'warm',
    description: 'Ontsteking en gasblok gecontroleerd na foutmelding',
    estimatedMinutes: 90,
    isUrgent: false,
    source: 'planned',
    technicians: [
      { technicianId: 'u1', name: 'Olivier Bossuyt', initials: 'OB', isLead: true, accepted: true, plannedOrder: 1 },
    ],
  },
  {
    id: 'i18',
    customerId: 'c10',
    customerName: 'WZC Lindepark',
    siteId: 's11',
    siteName: 'WZC Lindepark',
    siteAddress: 'Lindelaan 15',
    siteCity: 'Lebbeke',
    siteLat: 51.0058,
    siteLon: 4.1346,
    deviceId: 'd34',
    deviceBrand: 'Rational',
    deviceModel: 'iCombi Pro 10-1/1',
    plannedDate: '2026-02-03T09:00:00.000Z',
    status: 'afgewerkt',
    type: 'preventief',
    description: 'Preventief onderhoud en dichtingen gecontroleerd',
    estimatedMinutes: 100,
    isUrgent: false,
    source: 'planned',
    technicians: [
      { technicianId: 'u2', name: 'Jonas Declercq', initials: 'JD', isLead: true, accepted: true, plannedOrder: 1 },
    ],
  },
  {
    id: 'i19',
    customerId: 'c12',
    customerName: 'Ziekenhuis Sint-Blasius',
    siteId: 's13',
    siteName: 'Ziekenhuis Sint-Blasius',
    siteAddress: 'Kroonveldlaan 50',
    siteCity: 'Dendermonde',
    siteLat: 51.0241,
    siteLon: 4.1008,
    deviceId: 'd39',
    deviceBrand: 'Hobart',
    deviceModel: 'PREMAX CP',
    plannedDate: '2025-11-07T10:30:00.000Z',
    status: 'afgewerkt',
    type: 'warm',
    description: 'Doseerpomp en afvoerklep vervangen',
    estimatedMinutes: 140,
    isUrgent: true,
    source: 'planned',
    technicians: [
      { technicianId: 'u1', name: 'Olivier Bossuyt', initials: 'OB', isLead: true, accepted: true, plannedOrder: 1 },
    ],
  },
  {
    id: 'i20',
    customerId: 'c15',
    customerName: 'Pizzeria Da Luca',
    siteId: 's17',
    siteName: 'Pizzeria Da Luca',
    siteAddress: 'Nieuwstraat 14',
    siteCity: 'Lokeren',
    siteLat: 51.1049,
    siteLon: 3.9947,
    deviceId: 'd46',
    deviceBrand: 'Moretti Forni',
    deviceModel: 'T64E',
    plannedDate: '2026-01-14T11:00:00.000Z',
    status: 'afgewerkt',
    type: 'warm',
    description: 'Verwarmingselement vervangen in pizzaoven',
    estimatedMinutes: 110,
    isUrgent: false,
    source: 'planned',
    technicians: [
      { technicianId: 'u2', name: 'Jonas Declercq', initials: 'JD', isLead: true, accepted: true, plannedOrder: 1 },
    ],
  },

  // ── Today: job with device history ──────────────────────────────────────
  {
    id: 'i21',
    customerId: 'c1',
    customerName: 'Rustoord Ennea',
    siteId: 's1',
    siteName: 'Rustoord Ennea',
    siteAddress: 'Gasthuisstraat 12',
    siteCity: 'Sint-Niklaas',
    siteLat: 51.1286,
    siteLon: 4.213,
    deviceId: 'd10',
    deviceBrand: 'Winterhalter',
    deviceModel: 'PT-L',
    plannedDate: new Date().toISOString(),
    status: 'gepland',
    type: 'warm',
    description: 'Pomp lekt — water op vloer na spoelcyclus (herhaald probleem)',
    estimatedMinutes: 90,
    isUrgent: true,
    source: 'planned',
    technicians: [
      { technicianId: 'u1', name: 'Olivier Bossuyt', initials: 'OB', isLead: true, accepted: true, plannedOrder: 7 },
    ],
  },

  // ── Extra historical jobs for d10 (Winterhalter PT-L) ───────────────────
  {
    id: 'i22',
    customerId: 'c1',
    customerName: 'Rustoord Ennea',
    siteId: 's1',
    siteName: 'Rustoord Ennea',
    siteAddress: 'Gasthuisstraat 12',
    siteCity: 'Sint-Niklaas',
    siteLat: 51.1286,
    siteLon: 4.213,
    deviceId: 'd10',
    deviceBrand: 'Winterhalter',
    deviceModel: 'PT-L',
    plannedDate: '2025-09-15T07:30:00.000Z',
    status: 'afgewerkt',
    type: 'warm',
    description: 'Borstels versleten — volledige borstelhefset vervangen',
    estimatedMinutes: 120,
    isUrgent: false,
    source: 'planned',
    technicians: [
      { technicianId: 'u1', name: 'Olivier Bossuyt', initials: 'OB', isLead: true, accepted: true, plannedOrder: 1 },
    ],
  },
  {
    id: 'i23',
    customerId: 'c1',
    customerName: 'Rustoord Ennea',
    siteId: 's1',
    siteName: 'Rustoord Ennea',
    siteAddress: 'Gasthuisstraat 12',
    siteCity: 'Sint-Niklaas',
    siteLat: 51.1286,
    siteLon: 4.213,
    deviceId: 'd10',
    deviceBrand: 'Winterhalter',
    deviceModel: 'PT-L',
    plannedDate: '2024-03-22T08:00:00.000Z',
    status: 'afgewerkt',
    type: 'preventief',
    description: 'Jaarlijks preventief onderhoud — filters gereinigd, sproeiarm gecontroleerd',
    estimatedMinutes: 75,
    isUrgent: false,
    source: 'planned',
    technicians: [
      { technicianId: 'u2', name: 'Jonas Declercq', initials: 'JD', isLead: true, accepted: true, plannedOrder: 1 },
    ],
  },

  // ── Open pool jobs ───────────────────────────────────────────────────────
  {
    id: 'i24',
    customerId: 'c2',
    customerName: 'WZC Helianthus',
    siteId: 's3',
    siteName: 'WZC Helianthus — Merelbeke',
    siteAddress: 'Hundelgemsesteenweg 44',
    siteCity: 'Merelbeke',
    siteLat: 51.0249,
    siteLon: 3.7491,
    deviceId: 'd16',
    deviceBrand: 'Electrolux',
    deviceModel: 'SkyLine Pro 20GN',
    plannedDate: new Date().toISOString(),
    status: 'gepland',
    type: 'warm',
    description: 'Deur sluit niet correct — stoom ontsnapt tijdens cyclus',
    estimatedMinutes: 60,
    isUrgent: false,
    source: 'reactive',
    technicians: [
      { technicianId: 'u1', name: 'Olivier Bossuyt', initials: 'OB', isLead: true, accepted: false, plannedOrder: 0 },
    ],
  },
  {
    id: 'i25',
    customerId: 'c6',
    customerName: 'Hotel Scheldezicht',
    siteId: 's7',
    siteName: 'Hotel Scheldezicht',
    siteAddress: 'Kaai 4',
    siteCity: 'Temse',
    siteLat: 51.1261,
    siteLon: 4.2145,
    deviceId: 'd25',
    deviceBrand: 'Rational',
    deviceModel: 'iCombi Pro 6-1/1',
    plannedDate: new Date().toISOString(),
    status: 'gepland',
    type: 'warm',
    description: 'Stoomgenerator uitgevallen — volledig gas, geen stoom meer',
    estimatedMinutes: 150,
    isUrgent: true,
    source: 'reactive',
    technicians: [
      { technicianId: 'u2', name: 'Jonas Declercq', initials: 'JD', isLead: true, accepted: false, plannedOrder: 0 },
    ],
  },
]

const seedCreatedAt = new Date().toISOString()
const tomorrow = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString()
const nextWeek = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString()

export const tasks: Task[] = [
  {
    id: 't1',
    type: 'bellen',
    title: 'Bel klant voor vervolgbezoek',
    description: 'Bevestig wanneer het onderdeel binnenkomt en plan een nieuw bezoek in.',
    assigneeType: 'user',
    assigneeUserId: 'u1',
    createdByUserId: 'u3',
    priority: 'hoog',
    status: 'open',
    werkbonId: 'wb-i1',
    interventionId: 'i1',
    dueDate: tomorrow,
    createdAt: seedCreatedAt,
    updatedAt: seedCreatedAt,
  },
  {
    id: 't2',
    type: 'bestelling',
    title: 'Bestel sproeiarm set',
    description: 'Bestellen voor de Electrolux Glasswasher 50 op deze werkbon.',
    assigneeType: 'user',
    assigneeUserId: 'u4',
    createdByUserId: 'u1',
    priority: 'dringend',
    status: 'bezig',
    werkbonId: 'wb-i1',
    interventionId: 'i1',
    dueDate: tomorrow,
    createdAt: seedCreatedAt,
    updatedAt: seedCreatedAt,
  },
  {
    id: 't3',
    type: 'bericht',
    title: 'Vraag foto van typeplaatje op',
    description: 'Klant heeft serienummer niet bevestigd. Extra foto nodig voor magazijn.',
    assigneeType: 'user',
    assigneeUserId: 'u2',
    createdByUserId: 'u3',
    priority: 'normaal',
    status: 'wacht_op_info',
    werkbonId: 'wb-i2',
    interventionId: 'i2',
    dueDate: nextWeek,
    createdAt: seedCreatedAt,
    updatedAt: seedCreatedAt,
  },
]

// ============================================================
// USERS (demo users across the organization)
// ============================================================

export const users: User[] = [
  {
    id: 'u1',
    name: 'Olivier Pierrard',
    initials: 'OP',
    email: 'olivier@bossuyt-service.be',
    role: 'technician',
    active: true,
  },
  {
    id: 'u2',
    name: 'Jonas Declercq',
    initials: 'JD',
    email: 'jonas@bossuyt-service.be',
    role: 'technician',
    active: true,
  },
  {
    id: 'u3',
    name: 'Els Van Damme',
    initials: 'EV',
    email: 'els@bossuyt-service.be',
    role: 'admin',
    active: true,
  },
  {
    id: 'u4',
    name: 'Tom Magazijn',
    initials: 'TM',
    email: 'magazijn@bossuyt-service.be',
    role: 'warehouse',
    active: true,
  },
  {
    id: 'u5',
    name: 'Sarah HR',
    initials: 'SH',
    email: 'hr@bossuyt-service.be',
    role: 'hr',
    active: true,
  },
]

export const currentUserId = 'u1'

// ============================================================
// HELPER FUNCTIONS
// used to look up related data without a database
// ============================================================

// Get all sites for a customer
export function getSitesByCustomer(customerId: string): Site[] {
  return sites.filter(site => site.customerId === customerId)
}

// Get all devices for a site
export function getDevicesBySite(siteId: string): Device[] {
  return devices.filter(device => device.siteId === siteId)
}

// Get all contacts for a site
export function getContactsBySite(siteId: string): Contact[] {
  return contacts.filter(contact => contact.siteId === siteId)
}

// Get a single customer by id
export function getCustomerById(id: string): Customer | undefined {
  return customers.find(customer => customer.id === id)
}

// Get a single site by id
export function getSiteById(id: string): Site | undefined {
  return sites.find(site => site.id === id)
}

// Get a single device by id
export function getDeviceById(id: string): Device | undefined {
  return devices.find(device => device.id === id)
}

export function getUserById(id: string): User | undefined {
  return users.find(user => user.id === id)
}

export function getCurrentUser(): User | undefined {
  return getUserById(currentUserId)
}

export function getInterventionById(id: string): Intervention | undefined {
  return interventions.find(intervention => intervention.id === id)
}
